Fix/is qr hardware generic
zoltanarvai/metamask-mobile pull request #5
Opened 2022-04-22 13:26 UTC by fstream9

**Description**

Adds hardware label to account info and overview components

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #???

2022-04-22 14:08 UTC, zoltanarvai requested changes

2022-04-22 14:08 UTC, zoltanarvai commented on app/util/address/index.js
> +export function isHardwareAccount(address) {
Could `isQRHardwareAccount` be removed? or is it used at other locations too?

2022-04-22 14:08 UTC, zoltanarvai commented on app/util/address/index.js
> +		if ([KeyringTypes.qr, KeyringTypes.ledger].includes(keyring.type) && keyring.accounts.includes(address)) {
casing of the address my differ... use lowercase comparison

2022-04-22 14:11 UTC, GummyGod approved these changes

2022-04-22 15:23 UTC, fstream9 commented on app/util/address/index.js
> +export function isHardwareAccount(address) {
used elsewhere by QR UI

2022-04-22 15:46 UTC, fstream9 commented on app/util/address/index.js
> +		if ([KeyringTypes.qr, KeyringTypes.ledger].includes(keyring.type) && keyring.accounts.includes(address)) {
resolved 👍

2022-04-25 10:51 UTC, zoltanarvai approved these changes

2022-04-25 10:52 UTC, merged