Ledger TX Modals
zoltanarvai/metamask-mobile pull request #6
Opened 2022-04-22 13:31 UTC by GummyGod

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #???

2022-04-22 14:19 UTC, zoltanarvai requested changes

2022-04-22 14:19 UTC, zoltanarvai commented on ios/MetaMask.xcodeproj/project.pbxproj
> -		0FD509E0336BF221F6527B24 /* libPods-MetaMask.a in Frameworks */ = {isa = PBXBuildFile; fileRef = EA0FF04C201CE95ED7EEEA82 /* libPods-MetaMask.a */; };
you need to revert the changes on this file

2022-04-22 14:19 UTC, zoltanarvai commented on ios/MetaMask/MetaMaskDebug.entitlements
> -<dict>
revert the changes here

2022-04-22 14:19 UTC, zoltanarvai commented on ios/Podfile
> -	pod 'Permission-BluetoothPeripheral', :path => '../node_modules/react-native-permissions/ios/BluetoothPeripheral'
this change is not necessary

2022-04-22 14:19 UTC, zoltanarvai commented on ios/MetaMask/Info.plist
> +  <string>Metamask needs Bluetooth access to connect to external devices.</string>
you should not have these here

2022-04-22 14:19 UTC, zoltanarvai commented on app/reducers/modals/index.js
> +		case 'TOGGLE_LEDGER_TRANSACTION':
shall we call this device action? (can we use this same modal for transactions, signing messages, signing typed data?)

2022-04-22 14:19 UTC, zoltanarvai commented on app/components/Views/LedgerConnect/index.tsx
> +			console.log('err,', e);
remove console.logs pls

2022-04-22 14:19 UTC, zoltanarvai commented on app/components/Views/LedgerConnect/index.tsx
> +					<TouchableOpacity
why is this thing here?

2022-04-22 14:19 UTC, zoltanarvai commented on app/components/Views/LedgerConnect/Scan.tsx
> +				const bluetoothPermissionStatus = await request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL);
probably no need for this change

2022-04-22 14:19 UTC, zoltanarvai commented on app/components/UI/Tokens/index.js
> -					return !isZero(tokenBalances[address]) || isETH;
why change this?

2022-04-22 14:19 UTC, zoltanarvai commented on app/components/UI/LedgerModals/LedgerTransactionModal.tsx
> +const ledgerConnectImage = require('../../../images/ledger-connect.png');
we need two images... one for DARK MODE and one for LIGHT MODE

2022-04-22 14:19 UTC, zoltanarvai commented on app/components/UI/LedgerModals/LedgerTransactionFailModal.tsx
> +const ledgerConnectImage = require('../../../images/ledger-connect.png');
see my comment blow for images

2022-04-22 14:19 UTC, zoltanarvai commented on app/components/UI/LedgerModals/InfoBox.tsx
> +			backgroundColor: '#367bcf14',
no already existing colour for this one?

2022-04-22 14:26 UTC, GummyGod commented on app/components/UI/LedgerModals/InfoBox.tsx
> +			backgroundColor: '#367bcf14',
No color, this one is pretty custom

2022-04-22 14:26 UTC, GummyGod commented on app/components/UI/LedgerModals/LedgerTransactionFailModal.tsx
> +const ledgerConnectImage = require('../../../images/ledger-connect.png');
Same here, I kept the same image, i think it should be fine til we get the two versions

2022-04-22 14:27 UTC, GummyGod commented on app/components/UI/Tokens/index.js
> -					return !isZero(tokenBalances[address]) || isETH;
linter

2022-04-22 14:27 UTC, GummyGod commented on app/components/Views/LedgerConnect/Scan.tsx
> +				const bluetoothPermissionStatus = await request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL);
you suggested we keep request

2022-04-22 14:27 UTC, GummyGod commented on app/components/Views/LedgerConnect/index.tsx
> +					<TouchableOpacity
It is a way for me to test the modal's UI until we add the real logic. I'll comment it

2022-04-22 14:30 UTC, GummyGod commented on ios/MetaMask/Info.plist
> +  <string>Metamask needs Bluetooth access to connect to external devices.</string>
why?

2022-04-22 14:30 UTC, GummyGod commented on ios/Podfile
> -	pod 'Permission-BluetoothPeripheral', :path => '../node_modules/react-native-permissions/ios/BluetoothPeripheral'
fixed

2022-04-22 14:37 UTC, zoltanarvai commented on ios/MetaMask/Info.plist
> +  <string>Metamask needs Bluetooth access to connect to external devices.</string>
they should be coming from the main project... so not sure why you have them.

2022-04-22 14:46 UTC, fstream9 commented on app/components/UI/LedgerModals/LedgerTransactionFailModal.tsx
> +					<StyledButton type="cancel" onPress={() => null} style={styles.buttonStyle}>
shouldn't these buttons do something?

2022-04-22 14:46 UTC, fstream9 commented on app/components/UI/LedgerModals/LedgerTransactionModal.tsx
> +					<StyledButton type="cancel" onPress={() => null}>
same here, do something?

2022-04-22 14:46 UTC, fstream9 commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 875;
quite a big jump?

2022-04-25 10:37 UTC, GummyGod commented on app/components/UI/LedgerModals/LedgerTransactionFailModal.tsx
> +					<StyledButton type="cancel" onPress={() => null} style={styles.buttonStyle}>
Yes, but not atm, this is the MVP for them, we need to refactor first

2022-04-25 10:37 UTC, GummyGod commented on app/components/UI/LedgerModals/LedgerTransactionModal.tsx
> +					<StyledButton type="cancel" onPress={() => null}>
same

2022-04-25 10:38 UTC, GummyGod commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 875;
That was automatic

2022-04-27 10:34 UTC, zoltanarvai commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 875;
I never commit these in.... not sure what this does. Better not update?

2022-04-27 10:41 UTC, zoltanarvai commented on app/actions/modals/index.js
> +	type: 'TOGGLE_LEDGER_DEVICE_TRANSACTION',
We were saying that this is not about transaction. It's a generic DeviceAction.

We might use it for signing, transaction, personal message signing, typed data, etc.

I'd prefer to use `TOGGLE_LEDGER_DEVICE_ACTION`

and toggleLedgerDeviceActionModal

2022-04-27 10:41 UTC, zoltanarvai commented on app/components/UI/LedgerModals/LedgerTransactionModal.tsx
> +const ledgerConnectImage = require('../../../images/ledger-connect.png');
Can you ask Antonella to provide this? She has actually two of these images. (one with a bluetooth sign in the middle and one with a question mark)

2022-04-27 10:41 UTC, zoltanarvai commented on app/components/Views/LedgerConnect/index.tsx
> +					{/* <TouchableOpacity
we can safely remove this for now

2022-04-27 10:41 UTC, zoltanarvai commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 5.0.0;
definitely don't update this version please yourself

2022-04-27 10:58 UTC, zoltanarvai commented on app/components/Views/LedgerConnect/index.tsx
> +import { useDispatch } from 'react-redux';
this should be on the top as an import. (before local imports)

2022-04-27 10:58 UTC, zoltanarvai commented on app/reducers/modals/index.js
> +	ledgerTransactionModalVisible: false,
you didn't change the naming here

2022-04-27 10:58 UTC, zoltanarvai commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 875;
these changes are still here

2022-04-27 11:20 UTC, zoltanarvai approved these changes

2022-04-27 11:20 UTC, merged